# Generated by Django 5.1.4 on 2025-01-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('SUPLEMEN', 'SUPPLEMENT'), ('PERAWATAN DIRI', 'SELF CARE'), ('KESEHATAN DAN KECANTIKAN', 'HEALTH AND BEAUTY'), ('LAIN-LAIN', 'ETC')], max_length=25, null=True)),
            ],
        ),
    ]
