# Generated by Django 5.1.4 on 2025-01-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_products_category_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
