# Generated by Django 5.1.4 on 2025-04-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_order_alter_cart_cart_code_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
